
[control_plane]
control-plane ansible_host=100.58.211.235 private_ip=172.31.6.230

[workers_front]
worker-1 ansible_host=18.204.4.45 private_ip=172.31.11.31

[workers_back]
worker-2 ansible_host=3.239.70.171 private_ip=172.31.15.64
worker-3 ansible_host=18.204.4.46 private_ip=172.31.11.32

[workers_cluster:children]
workers_front
workers_back

[k8s_nodes:children]
control_plane
workers_front
workers_back

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/labsuser.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
