apiVersion: v1
kind: Service
metadata:
  name: lab-devops-api-service
  namespace: lab-devops
spec:
  selector:
    app: lab-devops-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: ClusterIP
